config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'stories#index'

  get '/about' => 'welcome#about'
  get '/faq' => 'welcome#faq'

  get '/authors' => 'authors#index'
  get '/authors/:slug' => 'authors#view', as: :author
  get '/:category' => 'stories#list', as: :category

  post '/subscribe' => 'subscription#all_weekly_digest'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :sources
  has_many :stories, through: :sources

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :bio, presence: true
  validates :slug, presence: true
  validates :slug, uniqueness: { case_sensitive: false }

  # how about a counter cache?
  def self.with_stories
    joins(:stories).uniq.all
  end

  def to_param
    slug
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :stories
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :sources

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :slug, presence: true
  validates :slug, uniqueness: { case_sensitive: false }
  validates :homepage, presence: true
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :author
  belongs_to :site
  has_many :stories

  validates :author, presence: true
  validates :author, uniqueness: { scope: :site,
    message: 'already added for the site' }
  validates :site, presence: true
  validates :url, presence: true
  validates :url, uniqueness: { case_sensitive: false }

  def to_s
    "#{author.name} for #{site.name}"
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :source
  belongs_to :category

  validates :title, presence: true
  validates :url, presence: true
  validates :url, uniqueness: { case_sensitive: false }

  scope :uncategorized, proc { where(:category_id => nil) }

  after_save :enqueue_index_story
  after_destroy :enqueue_remove_story_index

  # always the most recent first
  default_scope { order('published_at DESC') }

  private

  def enqueue_index_story
    IndexStoryJob.perform_later self.id
  end

  def enqueue_remove_story_index
    RemoveStoryIndexJob.perform_later self.id
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :populate_categories
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def populate_categories
    @navigations = Category.all
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.with_stories
  end

  def view
    @author = Author.find_by_slug(params[:slug])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @story_groups = prepare_groups
  end

  def list
    @category = Category.find_by(slug: params[:category])
    @story_groups = prepare_groups(@category)
  end

  private
  def prepare_groups(category = nil)
    story_groups = Hash.new

    today = Story.where('published_at >= ?', Time.zone.now.beginning_of_day).order(published_at: :desc, created_at: :desc)
    today = today.where(category: category) if category
    story_groups[:today] = {
      :label => 'Today',
      :name => Date.today.strftime("%B") + ' ' + Date.today.day.ordinalize,
      :stories => today
    }

    yesterday = Story.where(:published_at => Date.yesterday.beginning_of_day..Date.yesterday.end_of_day).order(published_at: :desc, created_at: :desc)
    yesterday = yesterday.where(category: category) if category
    story_groups[:yesterday] = {
      :label => 'Yesterday',
      :name => Date.yesterday.strftime('%B') + ' ' + Date.yesterday.day.ordinalize,
      :stories => yesterday
    }

    week = Story.where(:published_at => 7.days.ago.beginning_of_day..2.days.ago.end_of_day).order(published_at: :desc, created_at: :desc)
    week = week.where(category: category) if category
    story_groups[:week] = {
      :label => 'This Week',
      :stories => week
    }

    month = Story.where(:published_at => 30.days.ago.beginning_of_day..8.days.ago.end_of_day).order(published_at: :desc, created_at: :desc)
    month = month.where(category: category) if category
    story_groups[:month] = {
      :label => 'This Month',
      :stories => month
    }

    older = Story.where('published_at < ?', 31.days.ago.end_of_day).order(published_at: :desc, created_at: :desc).limit(50)
    older = older.where(category: category) if category
    story_groups[:older] = {
      :label => 'Older',
      :stories => older
    }

    story_groups
  end
end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController
  def all_weekly_digest
    email_address = params[:email_address]

    # simple email address validation
    if email_address !~ /@/
      success = false
      message = "The Email you gave isn't a valid one."
    else
      # check if exists already
      subscription = Subscription.find_by_email_address(email_address)
      if subscription
        success = true
        message = 'Looks like you are already signed up for our digest mails!'
      else
        if Subscription.create({:email_address => email_address})
          # add to weekly digest list
          SubscribeUserToWeeklyDigestJob.perform_later(email_address)

          success = true
          message = "Hello! We've signed you up for our weekly digest."

          # send greeting email
          DigestMailer.welcome(email_address).deliver_later
        else
          success = false
          message = "There was some problem subscribing you, try again in some time."
        end
      end

      cookies[:hide_subscription_banner] = {
        :value => true,
        :expires => 1.year.from_now
      };
    end

    respond_to do |format|
      format.json { render json:  {success: success, message: message} }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def faq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def nav_link(text, path, options = {})
    active_modifier = '--active'
    options[:class] = options[:class] + active_modifier if current_page?(path)
    content_tag(:li, link_to(text, path), options)
  end

  def site_link(text, path, options = {})
    active_modifier = '--active'

    recognized = Rails.application.routes.recognize_path(path)
    options[:class] = options[:class] + active_modifier if recognized[:controller] == params[:controller]
    link_to(text, path, options)
  end

  def inline_svg(filename, options = {})
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_author.html.erb
<li class="author-listing-card">
  <%= link_to author_path(author, { :class => 'author-listing-link' }) do %>
    <span class="author-listing-image"
          style="background-image: url(<%= asset_path 'authors/' + author.slug + '.jpg' %>)"></span>

    <h2 class="author-listing-name"><%= author.name %></h2>
    <small class="author-listing-meta"><%= pluralize author.stories.size, 'story' %></small>

    <p class="author-listing-bio"><%= author.bio %></p>
  <% end %>

  <a class="button author-listing-button" href="<%= author_path(author) %>">View</a>
</li>

app/views/authors/index.html.erb
<% title 'Authors' %>

<script type="text/javascript">
  mixpanel.track('Viewed Author Listing');
  mixpanel.track_links('.author-listing-card a', 'Opened an Author', function (element) {
    return {
      'Name': $(element).find('.author-listing-name').text()
    };
  });
</script>

<div class="l-container">
  <div class="l-page">
    <h1 class="l-page-header">Authors</h1>
    <h2 class="l-page-subheader">These are the <%= @authors.size %> fantastic authors we track.</h2>

    <ul class="author-listing">
      <%= render @authors %>
    </ul>
  </div>
</div>

app/views/authors/view.html.erb
<% title @author.name %>

<div class="l-container">
  <div class="l-page">
    <div class="author-details">
      <div class="author-details-header">
        <a class="button author-back-button" href="<%= authors_path %>">&#10094; Authors</a>
        <span class="author-details-image" style="background-image: url(<%= asset_path 'authors/' + @author.slug + '.jpg' %>)"></span>
        <h1 class="author-details-name"><%= @author.name %></h1>
        <% if @author.twitter_handle.present? %>
          <a class="author-details-twitter"
             href="http://www.twitter.com/<%= @author.twitter_handle %>"
             target="_blank">@<%= @author.twitter_handle %></a>
        <% end %>

        <p class="author-details-bio"><%= @author.bio %></p>
      </div>

      <ul class="author-details-article-listing">
        <% @author.stories.each do |story| %>
          <li class="author-details-article-item">
            <a href="<%= story.url %>" target="_blank">
              <small class="author-details-article-time"><%= distance_of_time_in_words(Time.now, story.published_at) %> ago</small>
              <h2 class="author-details-article-title"><%= story.title %></h2>
              <% if story.synopsis.present? %>
                <p class="author-details-article-synopsis"><%= story.synopsis %></p>
              <% end %>
            </a>
            <a class="author-details-article-link" href="<%= story.url %>" target="_blank">Read full story at <%= story.source.site.name %></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<%= render('shared/header') %>

<%= yield %>

<%= render('shared/footer') %>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Lato:300,400,700', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <meta name="description" content="GetRead.in is an aggregator of stories from well-read authors. Find the most in-depth and insightful stories from curated authors in one place.">

    <meta property="fb:admins" content="1578908806">
    <meta property="og:site_name" content="GetRead.in">
    <meta property="og:title" content="GetRead.in | Best stories in one place">
    <meta property="og:type" content="article">
    <meta property="og:image" content="http://www.getread.in/preview.png">
    <meta property="og:description" content="GetRead.in is an aggregator of stories from well-read authors. Find the most in-depth and insightful stories from curated authors in one place.">
    <meta property="og:locale" content="en_US">
    <meta property="og:url" content="http://www.getread.in/">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:site" content="@getreadin">
    <meta property="twitter:creator" content="@getreadin">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <%= csrf_meta_tags %>

    <title><%= yield(:title) + ' — ' if content_for?(:title) %> GetRead.in</title>

    <%= render('shared/google_analytics') %>
    <%= render('shared/mixpanel') %>

    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />

    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-precomposed-152.png">
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-precomposed-120.png">
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-precomposed-76.png">
    <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">

    <link href="https://plus.google.com/112749793626770941211" rel="publisher" />
  </head>
  <body class="<%= 'story-listing' if controller_name == 'stories' %>">

    <%= yield %>

  </body>
</html>

app/views/layouts/story.html.erb
<%= render('shared/navigation') %>

<%= yield %>

app/views/shared/_footer.html.erb
<footer class="l-footer l-container <%= 'is-border-less' if controller_name == 'stories' %>">
  Copyright &copy; <%= Date.today.year %> - GetRead.in
</footer>

app/views/shared/_google_analytics.html.erb
<% if Rails.env == 'production'  %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-66998842-1', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/shared/_header.html.erb
<header class="l-header">
  <div class="l-container">
    <div class="l-header-left">
      <a class="l-header-logo" href="<%= root_path %>">
        <%= inline_svg 'logo.svg' %>
      </a>

      <nav class="l-site-nav">
        <ul>
          <li class="l-site-navitem">
            <%= site_link 'Stories', root_path, :class => 'site-link' %>
          </li>
          <li class="l-site-navitem">
            <%= site_link 'Authors', authors_path, :class => 'site-link' %>
          </li>
          <li class="l-site-navitem">
            <div class="more-button">
              <%= inline_svg 'icon-more.svg' %>
              <label class="more-button-toggle-label" for="more-button-toggle-input"></label>
              <input class="more-button-toggle-input" id="more-button-toggle-input" type="checkbox">
              <ul class="more-button-callout">
                <%= nav_link 'About', about_path, :class => 'more-button-link' %>
                <%= nav_link 'FAQ', faq_path, :class => 'more-button-link' %>
              </ul>
            </div>
          </li>
        </ul>
      </nav>
    </div>

    <div class="l-header-right">
      <div class="l-header-search" href="#">
        <form class="search" onkeypress="return event.keyCode != 13;">
          <input class="search-input" name="query" id="query" type="search" placeholder="Search for featured stories and authors">
          <label class="search-label" for="query"><%= inline_svg 'icon-search.svg' %></label>
          <label class="search-close"><%= inline_svg 'icon-close.svg' %></label>
        </form>
      </div>
      <a class="l-header-login-button" href="#">Login</a>
    </div>
  </div>
</header>

app/views/shared/_mixpanel.html.erb
<% if Rails.env == 'production'  %>
<script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("3b60aedfed27c95d5ce159ad0f73f9e2");</script>
<% end %>

app/views/shared/_navigation.html.erb
<div class="l-navigation">
  <div class="l-container">
    <ul class="nav">
      <%= nav_link 'All', root_path, :class => 'nav-item' %>
      <% @navigations.each do |category| %>
        <%= nav_link category.title, category_url(category.slug), :class => 'nav-item' %>
      <% end %>
    </ul>
  </div>
</div>

app/views/stories/_listing.html.erb
<script type="text/javascript">
  mixpanel.track_links('.story', 'Opened a Story', function (element) {
    return {
      'Story URL': $(element).attr('href'),
      'Story Title': $(element).find('.story-title').text(),
      'Author': $(element).find('.story-author-image').data('author'),
      'Source Site': $(element).find('.story-site-image').data('site')
    };
  });
</script>

<ul class="l-listing">
  <% index = 0 %>
  <% story_groups.each do |key, group| %>
    <% next if group[:stories].size <= 0 %>

    <li class="l-listing-section">
      <div class="l-listing-header">
        <div class="section-heading">
          <h2 class="section-title"><%= group[:label] %></h3>
          <h3 class="section-descriptor"><%= group[:name] %></h4>
        </div>
      </div>

      <div class="l-container">
        <ul class="stories">
          <% group[:stories].each do |story| %>
            <% if index == 3 && !cookies[:hide_subscription_banner] %>
              <li class="l-subscription-item">
                <%= react_component('SubscriptionBannerItem', {}, {prerender: true}) %>
              </li>
            <% end %>

            <li class="l-story-item">
              <a class="story" href="<%= story.url %>" target="_blank">
                <span class="story-author-image-cell">
                  <span class="story-author-image"
                        data-author="<%= story.source.author.name %>"
                        style="background-image: url(<%= asset_path 'authors/' + story.source.author.slug + '.jpg' %>)"></span>
                </span>
                <span class="story-content-cell">
                  <h4 class="story-title"><%= story.title %></h4>
                  <small class="story-author-name"><%= story.source.author.name %></small>
                </span>
                <span class="story-site-image-cell">
                  <span class="story-site-image"
                        data-site="<%= story.source.site.name %>"
                        style="background-image: url(<%= asset_path 'sites/' + story.source.site.slug + '.png' %>)"></span>
                </span>
              </a>
            </li>
            <% index = index + 1 %>
          <% end %>
        </ul>
      </div>
    </li>
  <% end %>
</ul>

app/views/stories/index.html.erb
<script type="text/javascript">
  mixpanel.track('Viewed Homepage');
</script>

<%= render partial: 'listing', locals: {story_groups: @story_groups} %>

<% parent_layout "story" %>

app/views/stories/list.html.erb
<% title @category.title %>

<script type="text/javascript">
  mixpanel.track('Viewed Category Page', {
    Category: '<%= @category.title %>'
  });
</script>

<%= render partial: 'listing', locals: {story_groups: @story_groups} %>

<% parent_layout "story" %>

app/views/welcome/about.html.erb
<% title 'About' %>

<div class="l-container">
  <div class="l-page">
    <div class="about">
      <p class="about-hero">
        GetRead.in is a place to find the best content to read, every day. We track the best stories only from the best authors. It is meant for the people who are passionate about and appreciate good write-ups.
      </p>

      <p class="about-fineprint">
        We are an aggregator of stories from around publishers like Firstpost, Economic Times, Hindustan Times and Swarajya. All credit for the stories lie with them and we do not take credit for the stories and authors. We are passionate to improve the story reading experience by bringing the best stories in one place and allowing you to be able to remain notified about them.
      </p>

      <div class="faq-link">If you have any question, check out our <%= link_to('FAQ', faq_path) %></div>
      <div class="contact-mail">Or you could contact us at <a href="mailto:contact@getread.in">contact@getread.in</a></div>
    </div>
  </div>
</div>

app/views/welcome/faq.html.erb
<% title 'FAQ' %>

<div class="l-container">
  <div class="l-page">
    <h1 class="l-page-header">Frequently Asked Questions</h1>
    <h2 class="l-page-subheader"><%= link_to('Find information about us here', about_path) %></h2>

    <div class="faq-section">
      <h3 class="faq-question">
        What is GetRead.in?
      </h3>
      <p class="faq-answer">
        GetRead.in is the place to find an excellent collection of curated stories everyday. We track stories only from the best authors and list it.
      </p>

      <h3 class="faq-question">
        There is a good author that you missed, how do I submit the author?
      </h3>
      <p class="faq-answer">
        Currently we don't allow users to suggest authors. But it is currently a work in progress. Soon, you'll be able to suggest authors. We will check the suggestions and if we like we would start tracking them right away.
      </p>

      <h3 class="faq-question">
        Why do stories open on other sites?
      </h3>
      <p class="faq-answer">
        The stories we track are a property of their respective sites and publishers. We are simply an aggregator that brings all of them together. We strongly believe that the stories belong to the publishers and should stay with them. We simply want to improve the visibility of the stories and the authors who work hard on them. We hope that we would be able to do so.
      </p>

      <h3 class="faq-question">
        Do you have a mobile app?
      </h3>
      <p class="faq-answer">
        Right now we don't. We know we should. But we are working hard on building the base first. The work on the App will begin very soon. Keep watching this space.
      </p>

      <h3 class="faq-question">
        How can I reach you?
      </h3>
      <p class="faq-answer">
        Feel free to reach us by email at <a href="mailto:contact@getread.in">contact@getread.in</a> or on Twitter (<a href="http://www.twitter.com/getreadin">@GetReadin</a>).
      </p>
    </div>
  </div>
</div>